### ISSUE TITLE
Change use of auth.user to settings.AUTH_USER_MODEL

### ISSUE THREAD

**Issue by pwhipp** [ASKBOT/django-followit#7]
Otherwise stuff like askbot breaks via this package when one tries to integrate it into a Django app that uses a custom user model. See the django documentation [here](https://docs.djangoproject.com/en/1.8/topics/auth/customizing/) for more info.

**Comment by vchoi** [comment]
Maybe this is a stale issue, but the only direct reference I could find to auth.User is in followit/compat.py, where there's a reference to AUTH_USER_CLASS, which Google couldn't find anything about.

The way it's coded it will probably default to auth.User every time, therefore breaking django projects where the default django user model was replaced.

I suppose that should have been a reference to AUTH_USER_MODEL instead.

**Comment by evgenyfadeev** [comment]
yep, AUTH_USER_MODEL is supported
